import ch.qos.logback.core.rolling.TimeBasedFileNamingAndTriggeringPolicyBase;
public class FunctionUse1279 {
public void funcUse() {
TimeBasedFileNamingAndTriggeringPolicyBase timebasedfilenamingandtriggeringpolicybase = new TimeBasedFileNamingAndTriggeringPolicyBase();
timebasedfilenamingandtriggeringpolicybase.getCurrentPeriodsFileNameWithoutCompressionSuffix();
}
}